bug: fix the default sampling rate for AWS X-Ray tracer
suniltheta/envoy pull request #2
Opened 2021-04-13 01:57 UTC by suniltheta

Signed-off-by: Sunil Narasimhamurthy <sunnrs@amazon.com>

Commit Message: fix the default sampling rate for AWS X-Ray tracer extension to 5%
Additional Description:
Risk Level: Low
Testing: unit test the LocalizedSamplingStrategy to check if the default sampling rate is 0.05 is no other localized rule is applied via configuration
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

2021-04-13 02:11 UTC, lavignes requested changes
You'll want to update the release notes I think to call out the bug fix. version_history.rst?

2021-04-13 16:48 UTC, suniltheta commented
> You'll want to update the release notes I think to call out the bug fix. version_history.rst?

Updated the version history release notes to include the bug fix information.  Thanks for the tip.

2021-04-13 19:14 UTC, lavignes approved these changes

2021-04-22 16:37 UTC, suniltheta commented
Closing this review PR. Changes merged with PR 15958 on upstream repo.

2021-04-22 16:37 UTC, closed without merging